apiVersion: apps/v1

kind: Deployment

metadata:

  name: new-nginx-deployment

spec:

  selector:

    matchLabels:

      app: nginx

  replicas: 2 # tells deployment to run 2 pods matching the template

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx

        image: docker.io/jgvishnu/thakur:v1

        ports:

        - containerPort: 80


---
kind : Service
apiVersion : v1
metadata : 
  name: new-nginx-deployment
spec :
  selector :
    app : nginx
  ports :
  - protocol: TCP
    port: 80
    targetPort : 80
    nodePort: 32321
  type : NodePort
  externalIPs:
    - 172.18.0.2
    - 172.18.0.3  
